<template>
  <view class="page calculator-page">
    <view class="intro"><view class="title">IP 计算器</view><view class="desc">现场快速计算 IPv4 网段、掩码与地址容量</view></view>
    <view class="tabs"><view v-for="item in tabs" :key="item.value" :class="{active: activeTab === item.value}" @tap="activeTab = item.value">{{ item.label }}</view></view>
    <view v-if="activeTab === 'network'" class="panel form-panel"><view class="field-label">IPv4 地址</view><input v-model.trim="ip" class="input" placeholder="例如 192.168.10.20" /><view class="field-label">CIDR 掩码位</view><input v-model.trim="cidr" class="input" type="number" placeholder="例如 24" /><button class="primary-button" @tap="calculateNetwork">计算网段</button></view>
    <view v-else-if="activeTab === 'mask'" class="panel form-panel"><view class="field-label">CIDR 或子网掩码</view><input v-model.trim="maskInput" class="input" placeholder="例如 24 或 255.255.255.0" /><button class="primary-button" @tap="calculateMask">换算</button></view>
    <view v-else class="panel form-panel"><view class="field-label">需要的可用主机数</view><input v-model.trim="hosts" class="input" type="number" placeholder="例如 120" /><button class="primary-button" @tap="calculateHosts">推荐网段</button></view>
    <view v-if="error" class="error">{{ error }}</view>
    <view v-if="results.length" class="panel result-panel"><view class="result-title">计算结果</view><view v-for="row in results" :key="row.label" class="result-row" @tap="copy(row.value)"><text>{{ row.label }}</text><view><strong>{{ row.value }}</strong><text v-if="row.copyable" class="copy">复制</text></view></view></view>
  </view>
</template>
<script setup>
import { ref } from 'vue'
const tabs = [{ label: '网段计算', value: 'network' }, { label: '掩码换算', value: 'mask' }, { label: '地址容量', value: 'hosts' }]
const activeTab = ref('network'); const ip = ref(''); const cidr = ref('24'); const maskInput = ref(''); const hosts = ref(''); const results = ref([]); const error = ref('')
function parseIp(value) { const parts = String(value).trim().split('.'); if (parts.length !== 4 || parts.some((p) => !/^\d+$/.test(p) || Number(p) > 255)) throw new Error('请输入合法的 IPv4 地址'); return parts.map(Number) }
function toInt(value) { return parseIp(value).reduce((sum, part) => ((sum << 8) | part) >>> 0, 0) }
function toIp(value) { const n = Number(value) >>> 0; return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, n & 255].join('.') }
function validCidr(value) { const n = Number(value); if (!Number.isInteger(n) || n < 0 || n > 32) throw new Error('CIDR 必须是 0 到 32 的整数'); return n }
function maskFor(value) { const c = validCidr(value); return c ? (0xffffffff << (32 - c)) >>> 0 : 0 }
function maskToCidr(value) { const n = toInt(value); const binary = n.toString(2).padStart(32, '0'); if (!/^1*0*$/.test(binary)) throw new Error('请输入连续的子网掩码'); return binary.indexOf('0') < 0 ? 32 : binary.indexOf('0') }
function show(rows) { results.value = rows.map(([label, value, copyable = true]) => ({ label, value: String(value), copyable })); error.value = '' }
function calculateNetwork() { try { const c = validCidr(cidr.value); const current = toInt(ip.value); const mask = maskFor(c); const network = (current & mask) >>> 0; const broadcast = (network | (~mask >>> 0)) >>> 0; const total = 2 ** (32 - c); const usable = c <= 30 ? total - 2 : total; const first = c <= 30 ? network + 1 : network; const last = c <= 30 ? broadcast - 1 : broadcast; const binary = (value) => toIp(value).split('.').map((part) => Number(part).toString(2).padStart(8, '0')).join('.'); show([['CIDR 表示', `${ip.value}/${c}`], ['子网掩码', toIp(mask)], ['反掩码 / Wildcard Mask', toIp(~mask >>> 0)], ['网络地址', toIp(network)], ['广播地址', toIp(broadcast)], ['第一个可用地址', toIp(first)], ['最后一个可用地址', toIp(last)], ['可用地址范围', `${toIp(first)} - ${toIp(last)} `], ['总地址数', total, false], ['可用地址数', usable, false], ['IP 二进制', binary(current), false], ['掩码二进制', binary(mask), false], ['网络地址二进制', binary(network), false]]) } catch (e) { error.value = e.message; results.value = [] } }
function calculateMask() { try { const raw = maskInput.value.trim(); const c = raw.includes('.') ? maskToCidr(raw) : validCidr(raw); const mask = maskFor(c); show([['CIDR', `/${c}`], ['子网掩码', toIp(mask)], ['反掩码', toIp(~mask >>> 0)], ['掩码二进制', toIp(mask).split('.').map((p) => Number(p).toString(2).padStart(8, '0')).join('.') , false]]) } catch (e) { error.value = e.message; results.value = [] } }
function calculateHosts() { try { const count = Number(hosts.value); if (!Number.isInteger(count) || count < 1) throw new Error('请输入大于 0 的主机数'); let c = count === 1 ? 32 : 30; while (c > 0 && ((2 ** (32 - c)) - (c <= 30 ? 2 : 0)) < count) c -= 1; show([['推荐 CIDR', `/${c}`], ['推荐子网掩码', toIp(maskFor(c))], ['总地址数', 2 ** (32 - c), false], ['可用地址数', c <= 30 ? 2 ** (32 - c) - 2 : 2 ** (32 - c), false], ['说明', count === 2 ? '点到点链路可考虑 /31' : '选择可容纳该主机数的最小网段', false]]) } catch (e) { error.value = e.message; results.value = [] } }
function copy(value) { uni.setClipboardData({ data: String(value), success: () => uni.showToast({ title: '已复制', icon: 'success' }) }) }
</script>
<style scoped>
.calculator-page{padding:22rpx}.intro{padding:8rpx 4rpx 24rpx}.title{color:#1e2c3d;font-size:38rpx;font-weight:750}.desc{margin-top:9rpx;color:#788698;font-size:23rpx}.tabs{display:flex;margin-bottom:18rpx;padding:7rpx;border-radius:15rpx;background:#e8eef4}.tabs view{flex:1;padding:14rpx 4rpx;border-radius:10rpx;color:#718094;font-size:22rpx;text-align:center}.tabs view.active{background:#fff;color:#2765a8;font-weight:700}.form-panel{padding:24rpx}.field-label{margin:14rpx 0 9rpx;color:#4e5f73;font-size:23rpx}.input{height:80rpx;padding:0 18rpx;border:1rpx solid #dce4ed;border-radius:12rpx;background:#f9fbfc;color:#233349;font-size:26rpx}.primary-button{margin-top:26rpx;background:#286bc0;color:#fff}.error{margin:16rpx 2rpx;color:#c64c45;font-size:23rpx}.result-panel{margin-top:20rpx;padding:8rpx 24rpx}.result-title{padding:18rpx 0;color:#26384e;font-size:28rpx;font-weight:700}.result-row{display:flex;align-items:center;justify-content:space-between;gap:20rpx;padding:19rpx 0;border-top:1rpx solid #edf1f5}.result-row>text{color:#758397;font-size:22rpx}.result-row>view{display:flex;align-items:center;gap:14rpx;max-width:68%;text-align:right}.result-row strong{overflow:hidden;color:#293a50;font-size:24rpx;text-overflow:ellipsis;white-space:nowrap}.copy{padding:4rpx 9rpx;border-radius:7rpx;background:#edf5ff;color:#2a67aa;font-size:18rpx}
</style>
