"""task1 initial models

Revision ID: 2ec7d071134d
Revises:
Create Date: 2026-05-24 13:03:39.388886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec7d071134d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('min_role', sa.String(length=32), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("min_role in ('normal_user', 'org_admin', 'super_admin')", name='ck_app_menus_min_role'),
    sa.CheckConstraint("user_type in ('internal', 'external', 'system', 'all')", name='ck_app_menus_user_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_key')
    )
    op.create_table('org_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('active', 'disabled')", name='ck_org_units_status'),
    sa.CheckConstraint('level in (1, 2, 3)', name='ck_org_units_level'),
    sa.ForeignKeyConstraint(['parent_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.create_index('ix_org_units_level', ['level'], unique=False)
        batch_op.create_index('ix_org_units_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_org_units_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('oss_account', sa.String(length=64), nullable=True),
    sa.Column('oss_password_cipher', sa.Text(), nullable=True),
    sa.Column('oss_bind_status', sa.String(length=20), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_status', sa.String(length=20), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('manage_org_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("oss_bind_status in ('unbound', 'pending', 'bound', 'failed')", name='ck_users_oss_bind_status'),
    sa.CheckConstraint("password_status in ('initial', 'normal', 'locked')", name='ck_users_password_status'),
    sa.CheckConstraint("role_code in ('super_admin', 'org_admin', 'normal_user')", name='ck_users_role_code'),
    sa.CheckConstraint("status in ('active', 'disabled', 'pending')", name='ck_users_status'),
    sa.CheckConstraint("user_type in ('internal', 'external', 'system')", name='ck_users_user_type'),
    sa.ForeignKeyConstraint(['manage_org_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('oss_account')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_org_id', ['org_id'], unique=False)
        batch_op.create_index('ix_users_role_code', ['role_code'], unique=False)
        batch_op.create_index('ix_users_status', ['status'], unique=False)

    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login_account', sa.String(length=128), nullable=False),
    sa.Column('login_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('fail_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("result in ('success', 'fail')", name='ck_login_logs_result'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_logs')
    op.drop_table('login_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_status')
        batch_op.drop_index('ix_users_role_code')
        batch_op.drop_index('ix_users_org_id')

    op.drop_table('users')
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.drop_index('ix_org_units_status')
        batch_op.drop_index('ix_org_units_parent_id')
        batch_op.drop_index('ix_org_units_level')

    op.drop_table('org_units')
    op.drop_table('app_menus')
    # ### end Alembic commands ###
